"""Discovery of installed NSE scripts from Nmap's script database.

script.db is generated by ``nmap --script-updatedb`` and lists every script
with its categories. It is read as text; nothing from it is executed.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Optional

from genmap.core.nse import (
    CATEGORY_DESCRIPTIONS,
    INTRUSIVE_CATEGORIES,
    ScriptCatalog,
    ScriptEntry,
    ScriptExpressionError,
    ScriptSelection,
    select_scripts,
)

__all__ = [
    "CATEGORY_DESCRIPTIONS",
    "INTRUSIVE_CATEGORIES",
    "ScriptCatalog",
    "ScriptEntry",
    "ScriptExpressionError",
    "ScriptSelection",
    "load_script_catalog",
    "parse_script_db",
    "select_scripts",
]

log = logging.getLogger(__name__)

_ENTRY = re.compile(r'Entry\s*\{\s*filename\s*=\s*"(?P<file>[^"]+)"\s*,\s*categories\s*=\s*\{(?P<cats>[^}]*)\}')
_CATEGORY = re.compile(r'"([^"]+)"')


def parse_script_db(text: str) -> list[ScriptEntry]:
    entries: list[ScriptEntry] = []
    for match in _ENTRY.finditer(text):
        filename = match.group("file")
        name = filename[:-4] if filename.endswith(".nse") else filename
        categories = tuple(dict.fromkeys(_CATEGORY.findall(match.group("cats"))))
        entries.append(ScriptEntry(name, categories))
    entries.sort(key=lambda e: e.name)
    return entries


def load_script_catalog(data_directory: Optional[Path]) -> ScriptCatalog:
    if data_directory is None:
        return ScriptCatalog()
    path = data_directory / "scripts" / "script.db"
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        log.info("NSE script database not readable at %s: %s", path, exc)
        return ScriptCatalog()
    return ScriptCatalog(parse_script_db(text), path)
